CREATE TABLE TB_EMAIL (
    ID INT PRIMARY KEY IDENTITY(1,1),
    REMETENTE NVARCHAR(255) NOT NULL,
    DESTINATARIO NVARCHAR(255) NULL,
    CONTEUDO NVARCHAR(MAX) NULL,
    DATA_ENVIO DATETIME NULL,
    ERRO NVARCHAR(MAX) NULL
);


